export default {
  "12397fdc": [() => import(/* webpackChunkName: "12397fdc" */ "@site/src/pages/projects/index.md"), "@site/src/pages/projects/index.md", require.resolveWeak("@site/src/pages/projects/index.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "59c09780": [() => import(/* webpackChunkName: "59c09780" */ "C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json"), "C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json", require.resolveWeak("C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "72f3ba99": [() => import(/* webpackChunkName: "72f3ba99" */ "@site/docs/Projects/test.md"), "@site/docs/Projects/test.md", require.resolveWeak("@site/docs/Projects/test.md")],
  "8c4f3bfa": [() => import(/* webpackChunkName: "8c4f3bfa" */ "C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json"), "C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json", require.resolveWeak("C:\\JoySteem\\site-new\\joysteem\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],};
